version: '2'
services:
    aero_hack-app:
        image: aero_hack
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://aero_hack-postgresql:5432/aero_hack
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    aero_hack-postgresql:
        extends:
            file: postgresql.yml
            service: aero_hack-postgresql
